server:
  port: 8006

spring:
  application:
    name: consul-provider-order8006
  cloud:
    consul:   #consul设置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}