server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8002          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT  #通过轮询的方式进行调用，这里的lb是loadBalance负载均衡的意思
          predicates:
            - Path=/payment/getPaymentById/**         # 断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PROVIDER-PAYMENT  #通过轮询的方式进行调用，这里的lb是loadBalance负载均衡的意思
          predicates:  #RoutePredicateFactory路由断言工厂
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- After=2021-08-17T13:42:32.264+08:00[Asia/Shanghai]  #在哪个时间后才生效，ZonedDateTime time = ZonedDateTime.now()生成
            #- Before=2022-08-17T13:42:32.264+08:00[Asia/Shanghai]  #在哪个事件前才生效
            #- Between=2021-08-17T13:42:32.264+08:00[Asia/Shanghai],2022-08-17T13:42:32.264+08:00[Asia/Shanghai]  #在哪个时间段之间生效
            #- Cookie=username,ch.p  #请求中又cookid=ch***p才生效 curl http://localhost:9527/payment/lb --cookie "username=chip"
            #- Header=X-Request-Id, \d+ #请求中，包含请求头X-Request-Id并且是正数， curl http://localhost:9527/payment/lb -H "X-Request-Id:3" --cookie "username=chdp"
            #- Method=Get  #请求方式
            #- Query=age  #请求中包含请求参数age

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka