server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/git-shenjian/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
          username: git-shenjian
          password: shenjian520zhl
      ####分支
      label: master
  #http://localhost:3344/master/config-test.yml测试地址

#服务注册到eureka地址
eureka:
  instance:
    hostname: cloud-config-center
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka